export enum ReservationStatus {
  ACTIVE = 'ACTIVE',
  COMMITTED = 'COMMITTED',
  RELEASED = 'RELEASED',
  EXPIRED = 'EXPIRED',
}

export enum MovementType {
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  ADJUSTMENT = 'ADJUSTMENT',
  RESERVATION = 'RESERVATION',
  RELEASE = 'RELEASE',
}

export enum MovementReason {
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  IMPORT = 'IMPORT',
  RETURN = 'RETURN',
  DAMAGED = 'DAMAGED',
  WAREHOUSE_TRANSFER = 'WAREHOUSE_TRANSFER',
}
